In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [ ]:
# we have divided the code function by function
# first function is initialize_parameters
# this function initializes the parameters of the neural network
# here we just need to give in input the architecture of the neural network
# the architecture is given as a list of integers, where each integer represents the number of neurons
# so as per our archutecture will have 2 inputts, 2 in hidden layer and 1 output neuron
# so our architecture will be [2, 2, 1]
# so once we gave this to architecutre it will calculate the weights and biases which will be total 6 weights and 3 biases
# this will also provide value which we have given as 0.1 for weights and 0 for biases

def initialize_parameters(layer_dims):

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))


  return parameters

In [5]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [13]:
# we can see in o/p it has created 4 different arrays
# so w1 is basically the matrix of weights for the first layer
# so in w1  4 numbers which are basically initalization of weights
# so w1 is 2x2 matrix, so it has 2 rows and 2 columns
# so w1[0][0] is 0.1, w1[0][1] is 0.1, w1[1][0] is 0.1 and w1[1][1] is 0.1
# so w1[0][0] is the weight for the first input and first neuron
# w1[0][1] is the weight for the first input and second neuron
# w1[1][0] is the weight for the second input and first neuron  
# w1[1][1] is the weight for the second input and second neuron
# so b1 is the bias for the first layer, so it has 2 values, one for each neuron
# so b1[0] is the bias for the first neuron and b1[1] is the bias for the second neuron
# so w2 is the matrix of weights for the second layer, so it has 2 rows and 1 column
# so w2[0][0] is the weight for the first neuron and output neuron      
# w2[1][0] is the weight for the second neuron and output neuron
# so b2 is the bias for the second layer, so it has 1 value,
# so b2[0] is the bias for the output neuron
# so we have total 6 weights and 3 biases


In [ ]:
# what this function will do is for given any neuron it will calculate the output of that neuron
# so any neiuron has 5 inputs, 4 weights and 1 bias
# so it will take the input from the previous layer, multiply it with the weights and add the bias
# so this is the linear forward function


def linear_forward(A_prev, W, b):

  Z = np.dot(W.T, A_prev) + b

  return Z

In [ ]:
# Forward Prop

# this is my main function which will take the input and parameters and will calculate the output of the neural network
# so it will take the input and parameters and will calculate the output of the neural network
 

def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network

  for l in range(1, L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)

  return A,A_prev

In [ ]:
# so here basicall we are taking the input and parameters and calculating the output of the neural network
# so we are taking the input and parameters and calculating the output of the neural network



X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters) # call forward propagation function

In [16]:
y_hat,A1

(np.float64(0.32000000000000006),
 array([[1.6],
        [1.6]]))

In [19]:
# this function job is basically to update the parameters of the neural network
# so it will take the parameters, y, y_hat, A1 and X as input
# basically gradient descent is used to update the parameters of the neural network


def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [20]:
update_parameters(parameters,y,y_hat,A1,X)

In [21]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [22]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X, parameters)

In [24]:
y_hat,A1

(array([[0.52437005]]),
 array([[1.81270598],
        [1.81270598]]))

In [23]:
y_hat[0][0] # this will give us in number format the output of the neural network for the given input not in array format

np.float64(0.5243700464182887)

In [25]:
update_parameters(parameters,y,y_hat,A1,X)

C:\Users\saurabh.LAPTOP-2HELHMCR\AppData\Local\Temp\ipykernel_20268\3365919883.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
C:\Users\saurabh.LAPTOP-2HELHMCR\AppData\Local\Temp\ipykernel_20268\3365919883.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
C:\Users\saurabh.LAPTOP-2HELHMCR\AppData\Local\Temp\ipykernel_20268\3365919883.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract 

In [ ]:
parameters

# notice the output
# the paramerter has changed

{'W1': array([[0.11533984, 0.1276017 ],
        [0.11533984, 0.1276017 ]]),
 'b1': array([[0.00257437],
        [0.00257437]]),
 'W2': array([[0.13525283],
        [0.13525283]]),
 'b2': array([[0.14820409]])}

In [27]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [32]:

X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[1][0] # thisis for second row or student

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.26284038, 0.38271379],
        [0.27538569, 0.40643664]]),
 'b1': array([[0.02717114],
        [0.02936991]]),
 'W2': array([[0.40822626],
        [0.47800618]]),
 'b2': array([[0.47722371]])}

In [33]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[2][0] # tis is for 3rd student

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.26626641, 0.38842383],
        [0.27941201, 0.41314718]]),
 'b1': array([[0.02774214],
        [0.03004096]]),
 'W2': array([[0.41423368],
        [0.48681455]]),
 'b2': array([[0.48819301]])}

In [34]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[3][0] # 4th student

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.27131327, 0.40053629],
        [0.28538236, 0.42747601]]),
 'b1': array([[0.02875151],
        [0.03123503]]),
 'W2': array([[0.4254138 ],
        [0.50325707]]),
 'b2': array([[0.50562975]])}

In [35]:
# so in shortthe inner loop we had run 4 times for 4 student so outer loop ran 1 time that was for 1 epoch
# now same thing will repeat 5 times for 5 epochs
# for that will write a single piece of code which will run the inner loop 4 times and outer loop 5 times

In [36]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = [] # i will append the 4 stusdent loss in this list so that i can calculate the average loss for each epoch

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  25.321744156025517
Epoch -  2 Loss -  18.320004165722047
Epoch -  3 Loss -  9.473661050729628
Epoch -  4 Loss -  3.2520938634031613
Epoch -  5 Loss -  1.3407132589299962


{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}