In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [6]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2)) # 2 input features
model.add(Dense(1, activation='linear')) # 1 output feature

In [8]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.get_weights()
# so keras randomly initialized the weights and biases
# so the model that we created to make this similar will create new weight with weight 0.1 and bias 0
# and then wull call keras set_weights to set the weights and biases of keras model to the ones we created

new_weights = [np.array([[0.1, 0.1],
                          [0.1, 0.1]], dtype=np.float32),
                            np.array([0., 0.], dtype=np.float32), 
                            np.array([[0.1], 
                                      [0.1]], dtype=np.float32), 
                            np.array([0.], dtype=np.float32)] 

In [12]:
model.set_weights(new_weights)

In [13]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [15]:
# now ill go in optimiser and will set the learning rate to 0.01

optimizer = keras.optimizers.Adam(learning_rate=0.01)
# now i will compile the model with loss function as mean squared error and optimizer as adam
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [17]:
model.fit(df.iloc[:, 0:-1].values, df['lpa'].values, epochs=80, verbose=1, batch_size=1)

Epoch 1/80


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.1002  
Epoch 2/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.3933     
Epoch 3/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.6825 
Epoch 4/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8753 
Epoch 5/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9608 
Epoch 6/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.3138 
Epoch 7/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.4216 
Epoch 8/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.0458 
Epoch 9/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6645
Epoch 10/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7782 
Epoch 11/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.8420 
Epoch 12/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.2795 
Epoch 13/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0287 
Epoch 14/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.1819 
Epoch 15/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.2579 
Epoch 16/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 

In [ ]:
# lossis  areounf 0.1681
# its leess compared to what we did since we ran  for 80 epochs

In [18]:
model.get_weights()

[array([[-0.00361263, -0.00361263],
        [ 0.58456117,  0.58456117]], dtype=float32),
 array([0.22059105, 0.22059105], dtype=float32),
 array([[0.44899547],
        [0.44899547]], dtype=float32),
 array([0.23121366], dtype=float32)]