In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [3]:
df.head()

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [5]:
model = Sequential()

model.add(Dense(2, activation='sigmoid', input_dim=2)) # 2 input features
model.add(Dense(1, activation='sigmoid')) # 1 output feature

d:\SAURABH\spring 2024\DeepLearningProjects\customer_churn_prediction_using_ANN\.venv\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.get_weights()


[array([[ 0.92535126,  1.0697864 ],
        [-0.03033316, -0.99880815]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.2874776 ],
        [-0.29135513]], dtype=float32),
 array([0.], dtype=float32)]

In [9]:

new_weights = [np.array([[0.1, 0.1],
                          [0.1, 0.1]], dtype=np.float32),
                            np.array([0., 0.], dtype=np.float32), 
                            np.array([[0.1], 
                                      [0.1]], dtype=np.float32), 
                            np.array([0.], dtype=np.float32)] 

In [10]:
model.set_weights(new_weights)

In [11]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
# now ill go in optimiser and will set the learning rate to 0.001

optimizer = keras.optimizers.Adam(learning_rate=0.001)
# now i will compile the model with loss function as mean squared error and optimizer as adam
model.compile(loss='binary_crossentropy', optimizer=optimizer)

In [13]:
model.fit(df.iloc[:, 0:-1].values, df['placed'].values, epochs=80, verbose=1, batch_size=1)

Epoch 1/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.6572 
Epoch 2/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7148 
Epoch 3/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6561
Epoch 4/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6551 
Epoch 5/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6551 
Epoch 6/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6559 
Epoch 7/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6552
Epoch 8/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6561 
Epoch 9/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6562 
Epoch 10/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6556 
Epoch 11/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7139 
Epoch 12/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7066 
Epoch 13/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7166 
Epoch 14/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7062 
Epoch 15/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6720 
Epoch 16/80
4/4 ━━━━━━━━━━━━━━━━━

In [15]:
# even in this case for keras the loss is not moving ahead of 0.69
# but we are getting same loss function as we got in our backpropagation implementation
# so we can say that our implementation is correct
# so this what internally keras does